/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_westone_testdemo_skfTestNative */

#ifndef _Included_com_westone_testdemo_skfTestNative
#define _Included_com_westone_testdemo_skfTestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_westone_testdemo_skfTestNative
 * Method:    DevandAppTest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_westone_testdemo_skfTestNative_DevandAppTest
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
