// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Return.proto

#include "Return.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace com {
namespace westone {
namespace returncode {
class ResponsePackDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ResponsePack> _instance;
} _ResponsePack_default_instance_;
class Req_ErrorDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Req_Error> _instance;
} _Req_Error_default_instance_;
class Rsp_ErrorDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Rsp_Error> _instance;
} _Rsp_Error_default_instance_;
}  // namespace returncode
}  // namespace westone
}  // namespace com
static void InitDefaultsResponsePack_Return_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::westone::returncode::_ResponsePack_default_instance_;
    new (ptr) ::com::westone::returncode::ResponsePack();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::com::westone::returncode::ResponsePack::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ResponsePack_Return_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsResponsePack_Return_2eproto}, {}};

static void InitDefaultsReq_Error_Return_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::westone::returncode::_Req_Error_default_instance_;
    new (ptr) ::com::westone::returncode::Req_Error();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::com::westone::returncode::Req_Error::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Req_Error_Return_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReq_Error_Return_2eproto}, {}};

static void InitDefaultsRsp_Error_Return_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::westone::returncode::_Rsp_Error_default_instance_;
    new (ptr) ::com::westone::returncode::Rsp_Error();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::com::westone::returncode::Rsp_Error::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Rsp_Error_Return_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsRsp_Error_Return_2eproto}, {}};

void InitDefaults_Return_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_ResponsePack_Return_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Req_Error_Return_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Rsp_Error_Return_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_Return_2eproto[3];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_Return_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_Return_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_Return_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::com::westone::returncode::ResponsePack, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::com::westone::returncode::ResponsePack, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::com::westone::returncode::ResponsePack, ret_),
  PROTOBUF_FIELD_OFFSET(::com::westone::returncode::ResponsePack, content_),
  1,
  0,
  PROTOBUF_FIELD_OFFSET(::com::westone::returncode::Req_Error, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::com::westone::returncode::Req_Error, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::com::westone::returncode::Req_Error, ret_),
  0,
  PROTOBUF_FIELD_OFFSET(::com::westone::returncode::Rsp_Error, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::com::westone::returncode::Rsp_Error, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::com::westone::returncode::ResponsePack)},
  { 9, 15, sizeof(::com::westone::returncode::Req_Error)},
  { 16, 21, sizeof(::com::westone::returncode::Rsp_Error)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::com::westone::returncode::_ResponsePack_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::com::westone::returncode::_Req_Error_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::com::westone::returncode::_Rsp_Error_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_Return_2eproto = {
  {}, AddDescriptors_Return_2eproto, "Return.proto", schemas,
  file_default_instances, TableStruct_Return_2eproto::offsets,
  file_level_metadata_Return_2eproto, 3, file_level_enum_descriptors_Return_2eproto, file_level_service_descriptors_Return_2eproto,
};

const char descriptor_table_protodef_Return_2eproto[] =
  "\n\014Return.proto\022\026com.westone.returncode\","
  "\n\014ResponsePack\022\013\n\003ret\030\001 \002(\004\022\017\n\007content\030\002"
  " \001(\014\"\030\n\tReq_Error\022\013\n\003ret\030\001 \002(\004\"\013\n\tRsp_Er"
  "ror"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_Return_2eproto = {
  false, InitDefaults_Return_2eproto, 
  descriptor_table_protodef_Return_2eproto,
  "Return.proto", &assign_descriptors_table_Return_2eproto, 123,
};

void AddDescriptors_Return_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_Return_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_Return_2eproto = []() { AddDescriptors_Return_2eproto(); return true; }();
namespace com {
namespace westone {
namespace returncode {

// ===================================================================

void ResponsePack::InitAsDefaultInstance() {
}
class ResponsePack::HasBitSetters {
 public:
  static void set_has_ret(ResponsePack* msg) {
    msg->_has_bits_[0] |= 0x00000002u;
  }
  static void set_has_content(ResponsePack* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ResponsePack::kRetFieldNumber;
const int ResponsePack::kContentFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ResponsePack::ResponsePack()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.westone.returncode.ResponsePack)
}
ResponsePack::ResponsePack(const ResponsePack& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_content()) {
    content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
  ret_ = from.ret_;
  // @@protoc_insertion_point(copy_constructor:com.westone.returncode.ResponsePack)
}

void ResponsePack::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_ResponsePack_Return_2eproto.base);
  content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ret_ = PROTOBUF_ULONGLONG(0);
}

ResponsePack::~ResponsePack() {
  // @@protoc_insertion_point(destructor:com.westone.returncode.ResponsePack)
  SharedDtor();
}

void ResponsePack::SharedDtor() {
  content_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ResponsePack::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ResponsePack& ResponsePack::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ResponsePack_Return_2eproto.base);
  return *internal_default_instance();
}


void ResponsePack::Clear() {
// @@protoc_insertion_point(message_clear_start:com.westone.returncode.ResponsePack)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    content_.ClearNonDefaultToEmptyNoArena();
  }
  ret_ = PROTOBUF_ULONGLONG(0);
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ResponsePack::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ResponsePack*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // required uint64 ret = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_ret(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional bytes content = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        object = msg->mutable_content();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParser;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheck(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ResponsePack::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:com.westone.returncode.ResponsePack)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 ret = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {
          HasBitSetters::set_has_ret(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &ret_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bytes content = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_content()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:com.westone.returncode.ResponsePack)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.westone.returncode.ResponsePack)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ResponsePack::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.westone.returncode.ResponsePack)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint64 ret = 1;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->ret(), output);
  }

  // optional bytes content = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->content(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:com.westone.returncode.ResponsePack)
}

::google::protobuf::uint8* ResponsePack::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.westone.returncode.ResponsePack)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint64 ret = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->ret(), target);
  }

  // optional bytes content = 2;
  if (cached_has_bits & 0x00000001u) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->content(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.westone.returncode.ResponsePack)
  return target;
}

size_t ResponsePack::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.westone.returncode.ResponsePack)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required uint64 ret = 1;
  if (has_ret()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->ret());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional bytes content = 2;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->content());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ResponsePack::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.westone.returncode.ResponsePack)
  GOOGLE_DCHECK_NE(&from, this);
  const ResponsePack* source =
      ::google::protobuf::DynamicCastToGenerated<ResponsePack>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.westone.returncode.ResponsePack)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.westone.returncode.ResponsePack)
    MergeFrom(*source);
  }
}

void ResponsePack::MergeFrom(const ResponsePack& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.westone.returncode.ResponsePack)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _has_bits_[0] |= 0x00000001u;
      content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
    }
    if (cached_has_bits & 0x00000002u) {
      ret_ = from.ret_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ResponsePack::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.westone.returncode.ResponsePack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResponsePack::CopyFrom(const ResponsePack& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.westone.returncode.ResponsePack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResponsePack::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000002) != 0x00000002) return false;
  return true;
}

void ResponsePack::Swap(ResponsePack* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ResponsePack::InternalSwap(ResponsePack* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  content_.Swap(&other->content_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(ret_, other->ret_);
}

::google::protobuf::Metadata ResponsePack::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_Return_2eproto);
  return ::file_level_metadata_Return_2eproto[kIndexInFileMessages];
}


// ===================================================================

void Req_Error::InitAsDefaultInstance() {
}
class Req_Error::HasBitSetters {
 public:
  static void set_has_ret(Req_Error* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Req_Error::kRetFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Req_Error::Req_Error()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.westone.returncode.Req_Error)
}
Req_Error::Req_Error(const Req_Error& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ret_ = from.ret_;
  // @@protoc_insertion_point(copy_constructor:com.westone.returncode.Req_Error)
}

void Req_Error::SharedCtor() {
  ret_ = PROTOBUF_ULONGLONG(0);
}

Req_Error::~Req_Error() {
  // @@protoc_insertion_point(destructor:com.westone.returncode.Req_Error)
  SharedDtor();
}

void Req_Error::SharedDtor() {
}

void Req_Error::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Req_Error& Req_Error::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_Req_Error_Return_2eproto.base);
  return *internal_default_instance();
}


void Req_Error::Clear() {
// @@protoc_insertion_point(message_clear_start:com.westone.returncode.Req_Error)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ret_ = PROTOBUF_ULONGLONG(0);
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* Req_Error::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<Req_Error*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // required uint64 ret = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_ret(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool Req_Error::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:com.westone.returncode.Req_Error)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 ret = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {
          HasBitSetters::set_has_ret(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &ret_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:com.westone.returncode.Req_Error)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.westone.returncode.Req_Error)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void Req_Error::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.westone.returncode.Req_Error)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint64 ret = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->ret(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:com.westone.returncode.Req_Error)
}

::google::protobuf::uint8* Req_Error::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.westone.returncode.Req_Error)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint64 ret = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->ret(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.westone.returncode.Req_Error)
  return target;
}

size_t Req_Error::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.westone.returncode.Req_Error)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required uint64 ret = 1;
  if (has_ret()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->ret());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Req_Error::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.westone.returncode.Req_Error)
  GOOGLE_DCHECK_NE(&from, this);
  const Req_Error* source =
      ::google::protobuf::DynamicCastToGenerated<Req_Error>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.westone.returncode.Req_Error)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.westone.returncode.Req_Error)
    MergeFrom(*source);
  }
}

void Req_Error::MergeFrom(const Req_Error& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.westone.returncode.Req_Error)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_ret()) {
    set_ret(from.ret());
  }
}

void Req_Error::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.westone.returncode.Req_Error)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Req_Error::CopyFrom(const Req_Error& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.westone.returncode.Req_Error)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Req_Error::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void Req_Error::Swap(Req_Error* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Req_Error::InternalSwap(Req_Error* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(ret_, other->ret_);
}

::google::protobuf::Metadata Req_Error::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_Return_2eproto);
  return ::file_level_metadata_Return_2eproto[kIndexInFileMessages];
}


// ===================================================================

void Rsp_Error::InitAsDefaultInstance() {
}
class Rsp_Error::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Rsp_Error::Rsp_Error()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.westone.returncode.Rsp_Error)
}
Rsp_Error::Rsp_Error(const Rsp_Error& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:com.westone.returncode.Rsp_Error)
}

void Rsp_Error::SharedCtor() {
}

Rsp_Error::~Rsp_Error() {
  // @@protoc_insertion_point(destructor:com.westone.returncode.Rsp_Error)
  SharedDtor();
}

void Rsp_Error::SharedDtor() {
}

void Rsp_Error::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Rsp_Error& Rsp_Error::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_Rsp_Error_Return_2eproto.base);
  return *internal_default_instance();
}


void Rsp_Error::Clear() {
// @@protoc_insertion_point(message_clear_start:com.westone.returncode.Rsp_Error)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* Rsp_Error::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<Rsp_Error*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      default: {
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool Rsp_Error::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:com.westone.returncode.Rsp_Error)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:com.westone.returncode.Rsp_Error)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.westone.returncode.Rsp_Error)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void Rsp_Error::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.westone.returncode.Rsp_Error)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:com.westone.returncode.Rsp_Error)
}

::google::protobuf::uint8* Rsp_Error::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.westone.returncode.Rsp_Error)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.westone.returncode.Rsp_Error)
  return target;
}

size_t Rsp_Error::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.westone.returncode.Rsp_Error)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Rsp_Error::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.westone.returncode.Rsp_Error)
  GOOGLE_DCHECK_NE(&from, this);
  const Rsp_Error* source =
      ::google::protobuf::DynamicCastToGenerated<Rsp_Error>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.westone.returncode.Rsp_Error)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.westone.returncode.Rsp_Error)
    MergeFrom(*source);
  }
}

void Rsp_Error::MergeFrom(const Rsp_Error& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.westone.returncode.Rsp_Error)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void Rsp_Error::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.westone.returncode.Rsp_Error)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Rsp_Error::CopyFrom(const Rsp_Error& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.westone.returncode.Rsp_Error)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Rsp_Error::IsInitialized() const {
  return true;
}

void Rsp_Error::Swap(Rsp_Error* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Rsp_Error::InternalSwap(Rsp_Error* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
}

::google::protobuf::Metadata Rsp_Error::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_Return_2eproto);
  return ::file_level_metadata_Return_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace returncode
}  // namespace westone
}  // namespace com
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::com::westone::returncode::ResponsePack* Arena::CreateMaybeMessage< ::com::westone::returncode::ResponsePack >(Arena* arena) {
  return Arena::CreateInternal< ::com::westone::returncode::ResponsePack >(arena);
}
template<> PROTOBUF_NOINLINE ::com::westone::returncode::Req_Error* Arena::CreateMaybeMessage< ::com::westone::returncode::Req_Error >(Arena* arena) {
  return Arena::CreateInternal< ::com::westone::returncode::Req_Error >(arena);
}
template<> PROTOBUF_NOINLINE ::com::westone::returncode::Rsp_Error* Arena::CreateMaybeMessage< ::com::westone::returncode::Rsp_Error >(Arena* arena) {
  return Arena::CreateInternal< ::com::westone::returncode::Rsp_Error >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
