#ifndef __RETURN_CODE_H
#define __RETURN_CODE_H

#define RETURN_CODE_ERROR_BASE          0x90000000UL
#define RETURN_CODE_ERROR_PARAM		    (RETURN_CODE_ERROR_BASE + 1)
#define RETURN_CODE_ERROR_VERSION	    (RETURN_CODE_ERROR_BASE + 2)
#define RETURN_CODE_ERROR_TIMEOUT	    (RETURN_CODE_ERROR_BASE + 3)
#define RETURN_CODE_ERROR_NOT_SUPPORT	(RETURN_CODE_ERROR_BASE + 4)
#define RETURN_CODE_ERROR_PROTOCOL	    (RETURN_CODE_ERROR_BASE + 5)
#define RETURN_CODE_ERROR_CERT	        (RETURN_CODE_ERROR_BASE + 6)
#define RETURN_CODE_ERROR_COMM          (RETURN_CODE_ERROR_BASE + 7)
#define RETURN_CODE_ERROR_MONOPOLIZE_ALREADY (RETURN_CODE_ERROR_BASE + 8)
#endif //__RETURN_CODE_H
