// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Return.proto

#ifndef PROTOBUF_INCLUDED_Return_2eproto
#define PROTOBUF_INCLUDED_Return_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Return_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_Return_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_Return_2eproto();
namespace com {
namespace westone {
namespace returncode {
class Req_Error;
class Req_ErrorDefaultTypeInternal;
extern Req_ErrorDefaultTypeInternal _Req_Error_default_instance_;
class ResponsePack;
class ResponsePackDefaultTypeInternal;
extern ResponsePackDefaultTypeInternal _ResponsePack_default_instance_;
class Rsp_Error;
class Rsp_ErrorDefaultTypeInternal;
extern Rsp_ErrorDefaultTypeInternal _Rsp_Error_default_instance_;
}  // namespace returncode
}  // namespace westone
}  // namespace com
namespace google {
namespace protobuf {
template<> ::com::westone::returncode::Req_Error* Arena::CreateMaybeMessage<::com::westone::returncode::Req_Error>(Arena*);
template<> ::com::westone::returncode::ResponsePack* Arena::CreateMaybeMessage<::com::westone::returncode::ResponsePack>(Arena*);
template<> ::com::westone::returncode::Rsp_Error* Arena::CreateMaybeMessage<::com::westone::returncode::Rsp_Error>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace com {
namespace westone {
namespace returncode {

// ===================================================================

class ResponsePack final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.westone.returncode.ResponsePack) */ {
 public:
  ResponsePack();
  virtual ~ResponsePack();

  ResponsePack(const ResponsePack& from);

  inline ResponsePack& operator=(const ResponsePack& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResponsePack(ResponsePack&& from) noexcept
    : ResponsePack() {
    *this = ::std::move(from);
  }

  inline ResponsePack& operator=(ResponsePack&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ResponsePack& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResponsePack* internal_default_instance() {
    return reinterpret_cast<const ResponsePack*>(
               &_ResponsePack_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ResponsePack* other);
  friend void swap(ResponsePack& a, ResponsePack& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResponsePack* New() const final {
    return CreateMaybeMessage<ResponsePack>(nullptr);
  }

  ResponsePack* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResponsePack>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResponsePack& from);
  void MergeFrom(const ResponsePack& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResponsePack* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes content = 2;
  bool has_content() const;
  void clear_content();
  static const int kContentFieldNumber = 2;
  const ::std::string& content() const;
  void set_content(const ::std::string& value);
  #if LANG_CXX11
  void set_content(::std::string&& value);
  #endif
  void set_content(const char* value);
  void set_content(const void* value, size_t size);
  ::std::string* mutable_content();
  ::std::string* release_content();
  void set_allocated_content(::std::string* content);

  // required uint64 ret = 1;
  bool has_ret() const;
  void clear_ret();
  static const int kRetFieldNumber = 1;
  ::google::protobuf::uint64 ret() const;
  void set_ret(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:com.westone.returncode.ResponsePack)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr content_;
  ::google::protobuf::uint64 ret_;
  friend struct ::TableStruct_Return_2eproto;
};
// -------------------------------------------------------------------

class Req_Error final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.westone.returncode.Req_Error) */ {
 public:
  Req_Error();
  virtual ~Req_Error();

  Req_Error(const Req_Error& from);

  inline Req_Error& operator=(const Req_Error& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Req_Error(Req_Error&& from) noexcept
    : Req_Error() {
    *this = ::std::move(from);
  }

  inline Req_Error& operator=(Req_Error&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Req_Error& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Req_Error* internal_default_instance() {
    return reinterpret_cast<const Req_Error*>(
               &_Req_Error_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Req_Error* other);
  friend void swap(Req_Error& a, Req_Error& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Req_Error* New() const final {
    return CreateMaybeMessage<Req_Error>(nullptr);
  }

  Req_Error* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Req_Error>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Req_Error& from);
  void MergeFrom(const Req_Error& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Req_Error* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 ret = 1;
  bool has_ret() const;
  void clear_ret();
  static const int kRetFieldNumber = 1;
  ::google::protobuf::uint64 ret() const;
  void set_ret(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:com.westone.returncode.Req_Error)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint64 ret_;
  friend struct ::TableStruct_Return_2eproto;
};
// -------------------------------------------------------------------

class Rsp_Error final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.westone.returncode.Rsp_Error) */ {
 public:
  Rsp_Error();
  virtual ~Rsp_Error();

  Rsp_Error(const Rsp_Error& from);

  inline Rsp_Error& operator=(const Rsp_Error& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Rsp_Error(Rsp_Error&& from) noexcept
    : Rsp_Error() {
    *this = ::std::move(from);
  }

  inline Rsp_Error& operator=(Rsp_Error&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Rsp_Error& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Rsp_Error* internal_default_instance() {
    return reinterpret_cast<const Rsp_Error*>(
               &_Rsp_Error_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Rsp_Error* other);
  friend void swap(Rsp_Error& a, Rsp_Error& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Rsp_Error* New() const final {
    return CreateMaybeMessage<Rsp_Error>(nullptr);
  }

  Rsp_Error* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Rsp_Error>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Rsp_Error& from);
  void MergeFrom(const Rsp_Error& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Rsp_Error* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:com.westone.returncode.Rsp_Error)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Return_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ResponsePack

// required uint64 ret = 1;
inline bool ResponsePack::has_ret() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ResponsePack::clear_ret() {
  ret_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::uint64 ResponsePack::ret() const {
  // @@protoc_insertion_point(field_get:com.westone.returncode.ResponsePack.ret)
  return ret_;
}
inline void ResponsePack::set_ret(::google::protobuf::uint64 value) {
  _has_bits_[0] |= 0x00000002u;
  ret_ = value;
  // @@protoc_insertion_point(field_set:com.westone.returncode.ResponsePack.ret)
}

// optional bytes content = 2;
inline bool ResponsePack::has_content() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResponsePack::clear_content() {
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& ResponsePack::content() const {
  // @@protoc_insertion_point(field_get:com.westone.returncode.ResponsePack.content)
  return content_.GetNoArena();
}
inline void ResponsePack::set_content(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.westone.returncode.ResponsePack.content)
}
#if LANG_CXX11
inline void ResponsePack::set_content(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  content_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.westone.returncode.ResponsePack.content)
}
#endif
inline void ResponsePack::set_content(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.westone.returncode.ResponsePack.content)
}
inline void ResponsePack::set_content(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.westone.returncode.ResponsePack.content)
}
inline ::std::string* ResponsePack::mutable_content() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:com.westone.returncode.ResponsePack.content)
  return content_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ResponsePack::release_content() {
  // @@protoc_insertion_point(field_release:com.westone.returncode.ResponsePack.content)
  if (!has_content()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return content_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ResponsePack::set_allocated_content(::std::string* content) {
  if (content != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  content_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), content);
  // @@protoc_insertion_point(field_set_allocated:com.westone.returncode.ResponsePack.content)
}

// -------------------------------------------------------------------

// Req_Error

// required uint64 ret = 1;
inline bool Req_Error::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Req_Error::clear_ret() {
  ret_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::uint64 Req_Error::ret() const {
  // @@protoc_insertion_point(field_get:com.westone.returncode.Req_Error.ret)
  return ret_;
}
inline void Req_Error::set_ret(::google::protobuf::uint64 value) {
  _has_bits_[0] |= 0x00000001u;
  ret_ = value;
  // @@protoc_insertion_point(field_set:com.westone.returncode.Req_Error.ret)
}

// -------------------------------------------------------------------

// Rsp_Error

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace returncode
}  // namespace westone
}  // namespace com

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_Return_2eproto
