#ifndef __RETURN_CODE_H
#define __RETURN_CODE_H

#define RETURN_CODE_OK				0
#define RETURN_CODE_ERROR_PARAM		1
#define RETURN_CODE_ERROR_VERSION	2
#define RETURN_CODE_ERROR_TIMEOUT	3
#define RETURN_CODE_ERROR_SYSTEM	4
#define RETURN_CODE_NOT_SUPPORT		5

#endif //__RETURN_CODE_H
