/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_westone_skf_SkfNativeFunc */

#ifndef _Included_com_westone_skf_SkfNativeFunc
#define _Included_com_westone_skf_SkfNativeFunc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    regCallback
 * Signature: (Lcom/westone/skf/SkfCallback;)V
 */
JNIEXPORT void JNICALL Java_com_westone_skf_SkfNativeFunc_regCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_EnumDev
 * Signature: (Ljava/util/List;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1EnumDev
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_ConnectDev
 * Signature: (Ljava/lang/String;Lcom/westone/skf/DEVHANDLE;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1ConnectDev
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_DisConnectDev
 * Signature: (Lcom/westone/skf/DEVHANDLE;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1DisConnectDev
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_GetDevState
 * Signature: (Ljava/lang/String;Lcom/westone/skf/DevState;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1GetDevState
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_SetLabel
 * Signature: (Lcom/westone/skf/DEVHANDLE;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1SetLabel
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_GetDevInfo
 * Signature: (Lcom/westone/skf/DEVHANDLE;Lcom/westone/skf/DEVINFO;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1GetDevInfo
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_LockDev
 * Signature: (Lcom/westone/skf/DEVHANDLE;J)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1LockDev
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_UnlockDev
 * Signature: (Lcom/westone/skf/DEVHANDLE;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1UnlockDev
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_ChangeDevAuthKey
 * Signature: (Lcom/westone/skf/DEVHANDLE;[B)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1ChangeDevAuthKey
  (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_DevAuth
 * Signature: (Lcom/westone/skf/DEVHANDLE;[B)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1DevAuth
  (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_ChangePIN
 * Signature: (Lcom/westone/skf/HAPPLICATION;JLjava/lang/String;Ljava/lang/String;Lcom/westone/skf/PinRetryCount;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1ChangePIN
  (JNIEnv *, jclass, jobject, jlong, jstring, jstring, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_GetPINInfo
 * Signature: (Lcom/westone/skf/HAPPLICATION;JLcom/westone/skf/PinInfo;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1GetPINInfo
  (JNIEnv *, jclass, jobject, jlong, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_VerifyPIN
 * Signature: (Lcom/westone/skf/HAPPLICATION;JLjava/lang/String;Lcom/westone/skf/PinRetryCount;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1VerifyPIN
  (JNIEnv *, jclass, jobject, jlong, jstring, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_UnblockPIN
 * Signature: (Lcom/westone/skf/HAPPLICATION;Ljava/lang/String;Ljava/lang/String;Lcom/westone/skf/PinRetryCount;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1UnblockPIN
  (JNIEnv *, jclass, jobject, jstring, jstring, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_ClearSecureState
 * Signature: (Lcom/westone/skf/HAPPLICATION;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1ClearSecureState
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_CreateApplication
 * Signature: (Lcom/westone/skf/DEVHANDLE;Ljava/lang/String;Ljava/lang/String;JLjava/lang/String;JJLcom/westone/skf/HAPPLICATION;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1CreateApplication
  (JNIEnv *, jclass, jobject, jstring, jstring, jlong, jstring, jlong, jlong, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_EnumApplication
 * Signature: (Lcom/westone/skf/DEVHANDLE;Ljava/util/List;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1EnumApplication
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_DeleteApplication
 * Signature: (Lcom/westone/skf/DEVHANDLE;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1DeleteApplication
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_OpenApplication
 * Signature: (Lcom/westone/skf/DEVHANDLE;Ljava/lang/String;Lcom/westone/skf/HAPPLICATION;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1OpenApplication
  (JNIEnv *, jclass, jobject, jstring, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_CloseApplication
 * Signature: (Lcom/westone/skf/HAPPLICATION;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1CloseApplication
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_CreateFile
 * Signature: (Lcom/westone/skf/HAPPLICATION;Ljava/lang/String;JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1CreateFile
  (JNIEnv *, jclass, jobject, jstring, jlong, jlong, jlong);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_DeleteFile
 * Signature: (Lcom/westone/skf/HAPPLICATION;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1DeleteFile
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_EnumFiles
 * Signature: (Lcom/westone/skf/HAPPLICATION;Ljava/util/List;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1EnumFiles
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_GetFileInfo
 * Signature: (Lcom/westone/skf/HAPPLICATION;Ljava/lang/String;Lcom/westone/skf/FILEATTRIBUTE;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1GetFileInfo
  (JNIEnv *, jclass, jobject, jstring, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_ReadFile
 * Signature: (Lcom/westone/skf/HAPPLICATION;Ljava/lang/String;JJ[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1ReadFile
  (JNIEnv *, jclass, jobject, jstring, jlong, jlong, jbyteArray, jlongArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_WriteFile
 * Signature: (Lcom/westone/skf/HAPPLICATION;Ljava/lang/String;J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1WriteFile
  (JNIEnv *, jclass, jobject, jstring, jlong, jbyteArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_CreateContainer
 * Signature: (Lcom/westone/skf/HAPPLICATION;Ljava/lang/String;Lcom/westone/skf/HCONTAINER;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1CreateContainer
  (JNIEnv *, jclass, jobject, jstring, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_DeleteContainer
 * Signature: (Lcom/westone/skf/HAPPLICATION;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1DeleteContainer
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_OpenContainer
 * Signature: (Lcom/westone/skf/HAPPLICATION;Ljava/lang/String;Lcom/westone/skf/HCONTAINER;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1OpenContainer
  (JNIEnv *, jclass, jobject, jstring, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_CloseContainer
 * Signature: (Lcom/westone/skf/HCONTAINER;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1CloseContainer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_EnumContainer
 * Signature: (Lcom/westone/skf/HAPPLICATION;Ljava/util/List;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1EnumContainer
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_GetContainerType
 * Signature: (Lcom/westone/skf/HCONTAINER;[J)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1GetContainerType
  (JNIEnv *, jclass, jobject, jlongArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_GenRandom
 * Signature: (Lcom/westone/skf/DEVHANDLE;[BJ)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1GenRandom
  (JNIEnv *, jclass, jobject, jbyteArray, jlong);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_GenExtRSAKey
 * Signature: (Lcom/westone/skf/DEVHANDLE;JLcom/westone/skf/RSAPRIVATEKEYBLOB;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1GenExtRSAKey
  (JNIEnv *, jclass, jobject, jlong, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_GenRSAKeyPair
 * Signature: (Lcom/westone/skf/HCONTAINER;JLcom/westone/skf/RSAPUBLICKEYBLOB;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1GenRSAKeyPair
  (JNIEnv *, jclass, jobject, jlong, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_ImportRSAKeyPair
 * Signature: (Lcom/westone/skf/HCONTAINER;J[B[B)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1ImportRSAKeyPair
  (JNIEnv *, jclass, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_RSASignData
 * Signature: (Lcom/westone/skf/HANDLE;[B[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1RSASignData
  (JNIEnv *, jclass, jobject, jbyteArray, jbyteArray, jlongArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_RSAVerify
 * Signature: (Lcom/westone/skf/DEVHANDLE;Lcom/westone/skf/RSAPUBLICKEYBLOB;[B[B)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1RSAVerify
  (JNIEnv *, jclass, jobject, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_RSAExportSessionKey
 * Signature: (Lcom/westone/skf/HCONTAINER;JLcom/westone/skf/RSAPUBLICKEYBLOB;[B[JLcom/westone/skf/HANDLE;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1RSAExportSessionKey
  (JNIEnv *, jclass, jobject, jlong, jobject, jbyteArray, jlongArray, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_ExtRSAPubKeyOperation
 * Signature: (Lcom/westone/skf/DEVHANDLE;Lcom/westone/skf/RSAPUBLICKEYBLOB;[B[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1ExtRSAPubKeyOperation
  (JNIEnv *, jclass, jobject, jobject, jbyteArray, jbyteArray, jlongArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_ExtRSAPriKeyOperation
 * Signature: (Lcom/westone/skf/DEVHANDLE;Lcom/westone/skf/RSAPRIVATEKEYBLOB;[B[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1ExtRSAPriKeyOperation
  (JNIEnv *, jclass, jobject, jobject, jbyteArray, jbyteArray, jlongArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_GenECCKeyPair
 * Signature: (Lcom/westone/skf/HCONTAINER;JLcom/westone/skf/ECCPUBLICKEYBLOB;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1GenECCKeyPair
  (JNIEnv *, jclass, jobject, jlong, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_ImportECCKeyPair
 * Signature: (Lcom/westone/skf/HCONTAINER;Lcom/westone/skf/ENVELOPEDKEYBLOB;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1ImportECCKeyPair
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_ECCSignData
 * Signature: (Lcom/westone/skf/HCONTAINER;[BLcom/westone/skf/ECCSIGNATUREBLOB;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1ECCSignData
  (JNIEnv *, jclass, jobject, jbyteArray, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_ECCVerify
 * Signature: (Lcom/westone/skf/DEVHANDLE;Lcom/westone/skf/ECCPUBLICKEYBLOB;[BLcom/westone/skf/ECCSIGNATUREBLOB;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1ECCVerify
  (JNIEnv *, jclass, jobject, jobject, jbyteArray, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_ECCExportSessionKey
 * Signature: (Lcom/westone/skf/HCONTAINER;JLcom/westone/skf/ECCPUBLICKEYBLOB;Lcom/westone/skf/ECCCIPHERBLOB;Lcom/westone/skf/HANDLE;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1ECCExportSessionKey
  (JNIEnv *, jclass, jobject, jlong, jobject, jobject, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_ExtECCEncrypt
 * Signature: (Lcom/westone/skf/DEVHANDLE;Lcom/westone/skf/ECCPUBLICKEYBLOB;[BLcom/westone/skf/ECCCIPHERBLOB;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1ExtECCEncrypt
  (JNIEnv *, jclass, jobject, jobject, jbyteArray, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_ExtECCDecrypt
 * Signature: (Lcom/westone/skf/DEVHANDLE;Lcom/westone/skf/ECCPRIVATEKEYBLOB;Lcom/westone/skf/ECCCIPHERBLOB;[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1ExtECCDecrypt
  (JNIEnv *, jclass, jobject, jobject, jobject, jbyteArray, jlongArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_ExtECCSign
 * Signature: (Lcom/westone/skf/DEVHANDLE;Lcom/westone/skf/ECCPRIVATEKEYBLOB;[BLcom/westone/skf/ECCSIGNATUREBLOB;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1ExtECCSign
  (JNIEnv *, jclass, jobject, jobject, jbyteArray, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_ExtECCVerify
 * Signature: (Lcom/westone/skf/DEVHANDLE;Lcom/westone/skf/ECCPUBLICKEYBLOB;[BLcom/westone/skf/ECCSIGNATUREBLOB;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1ExtECCVerify
  (JNIEnv *, jclass, jobject, jobject, jbyteArray, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_GenerateAgreementDataWithECC
 * Signature: (Lcom/westone/skf/HCONTAINER;JLcom/westone/skf/ECCPUBLICKEYBLOB;[BLcom/westone/skf/HANDLE;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1GenerateAgreementDataWithECC
  (JNIEnv *, jclass, jobject, jlong, jobject, jbyteArray, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_GenerateAgreementDataAndKeyWithECC
 * Signature: (Lcom/westone/skf/HANDLE;JLcom/westone/skf/ECCPUBLICKEYBLOB;Lcom/westone/skf/ECCPUBLICKEYBLOB;Lcom/westone/skf/ECCPUBLICKEYBLOB;[B[BLcom/westone/skf/HANDLE;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1GenerateAgreementDataAndKeyWithECC
  (JNIEnv *, jclass, jobject, jlong, jobject, jobject, jobject, jbyteArray, jbyteArray, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_GenerateKeyWithECC
 * Signature: (Lcom/westone/skf/HANDLE;Lcom/westone/skf/ECCPUBLICKEYBLOB;Lcom/westone/skf/ECCPUBLICKEYBLOB;[BLcom/westone/skf/HANDLE;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1GenerateKeyWithECC
  (JNIEnv *, jclass, jobject, jobject, jobject, jbyteArray, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_ExportPublicKey
 * Signature: (Lcom/westone/skf/HCONTAINER;Z[Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1ExportPublicKey
  (JNIEnv *, jclass, jobject, jboolean, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_ImportSessionKey
 * Signature: (Lcom/westone/skf/HCONTAINER;JLjava/lang/Object;Lcom/westone/skf/HANDLE;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1ImportSessionKey
  (JNIEnv *, jclass, jobject, jlong, jobject, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_SetSymmKey
 * Signature: (Lcom/westone/skf/DEVHANDLE;[BJLcom/westone/skf/HANDLE;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1SetSymmKey
  (JNIEnv *, jclass, jobject, jbyteArray, jlong, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_EncryptInit
 * Signature: (Lcom/westone/skf/HANDLE;Lcom/westone/skf/BLOCKCIPHERPARAM;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1EncryptInit
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_Encrypt
 * Signature: (Lcom/westone/skf/HANDLE;[B[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1Encrypt
  (JNIEnv *, jclass, jobject, jbyteArray, jbyteArray, jlongArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_EncryptUpdate
 * Signature: (Lcom/westone/skf/HANDLE;[B[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1EncryptUpdate
  (JNIEnv *, jclass, jobject, jbyteArray, jbyteArray, jlongArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_EncryptFinal
 * Signature: (Lcom/westone/skf/HANDLE;[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1EncryptFinal
  (JNIEnv *, jclass, jobject, jbyteArray, jlongArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_DecryptInit
 * Signature: (Lcom/westone/skf/HANDLE;Lcom/westone/skf/BLOCKCIPHERPARAM;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1DecryptInit
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_Decrypt
 * Signature: (Lcom/westone/skf/HANDLE;[B[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1Decrypt
  (JNIEnv *, jclass, jobject, jbyteArray, jbyteArray, jlongArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_DecryptUpdate
 * Signature: (Lcom/westone/skf/HANDLE;[B[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1DecryptUpdate
  (JNIEnv *, jclass, jobject, jbyteArray, jbyteArray, jlongArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_DecryptFinal
 * Signature: (Lcom/westone/skf/HANDLE;[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1DecryptFinal
  (JNIEnv *, jclass, jobject, jbyteArray, jlongArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_DigestInit
 * Signature: (Lcom/westone/skf/DEVHANDLE;JLcom/westone/skf/ECCPUBLICKEYBLOB;[BLcom/westone/skf/HANDLE;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1DigestInit
  (JNIEnv *, jclass, jobject, jlong, jobject, jbyteArray, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_Digest
 * Signature: (Lcom/westone/skf/HANDLE;[B[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1Digest
  (JNIEnv *, jclass, jobject, jbyteArray, jbyteArray, jlongArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_DigestUpdate
 * Signature: (Lcom/westone/skf/HANDLE;[B)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1DigestUpdate
  (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_DigestFinal
 * Signature: (Lcom/westone/skf/HANDLE;[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1DigestFinal
  (JNIEnv *, jclass, jobject, jbyteArray, jlongArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_MacInit
 * Signature: (Lcom/westone/skf/HANDLE;Lcom/westone/skf/BLOCKCIPHERPARAM;Lcom/westone/skf/HANDLE;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1MacInit
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_Mac
 * Signature: (Lcom/westone/skf/HANDLE;[B[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1Mac
  (JNIEnv *, jclass, jobject, jbyteArray, jbyteArray, jlongArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_MacUpdate
 * Signature: (Lcom/westone/skf/HANDLE;[B)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1MacUpdate
  (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_MacFinal
 * Signature: (Lcom/westone/skf/HANDLE;[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1MacFinal
  (JNIEnv *, jclass, jobject, jbyteArray, jlongArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_CloseHandle
 * Signature: (Lcom/westone/skf/HANDLE;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1CloseHandle
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_Transmit
 * Signature: (Lcom/westone/skf/DEVHANDLE;[B[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1Transmit
  (JNIEnv *, jclass, jobject, jbyteArray, jbyteArray, jlongArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_ImportCertificate
 * Signature: (Lcom/westone/skf/HCONTAINER;Z[B)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1ImportCertificate
  (JNIEnv *, jclass, jobject, jboolean, jbyteArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_ExportCertificate
 * Signature: (Lcom/westone/skf/HCONTAINER;Z[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1ExportCertificate
  (JNIEnv *, jclass, jobject, jboolean, jbyteArray, jlongArray);

/*
 * Class:     com_westone_skf_SkfNativeFunc
 * Method:    SKF_GetContainerProperty
 * Signature: (Lcom/westone/skf/HCONTAINER;[J)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1GetContainerProperty
  (JNIEnv *, jclass, jobject, jlongArray);

JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1CreateSoftCard(JNIEnv *env, jclass clazz);

JNIEXPORT jlong JNICALL Java_com_westone_skf_SkfNativeFunc_SKF_1DeleteSoftCard(JNIEnv *env, jclass clazz);

JNIEXPORT void JNICALL Java_com_westone_skf_SkfNativeFunc_setLibPath(JNIEnv *env, jclass clazz, jobject ct,jstring libPath);

#ifdef __cplusplus
}
#endif
#endif
