/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_westone_cardmanager_Card */

#ifndef _Included_com_westone_cardmanager_Card
#define _Included_com_westone_cardmanager_Card
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_westone_cardmanager_Card
 * Method:    GetCard
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_westone_cardmanager_Card_GetCard
  (JNIEnv *, jclass);

/*
 * Class:     com_westone_cardmanager_Card
 * Method:    GetCardStatus
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_westone_cardmanager_Card_GetCardStatus
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_westone_cardmanager_Card
 * Method:    RegCardStatusCallback
 * Signature: (Lcom/westone/cardmanager/ITFStatus;)V
 */
JNIEXPORT void JNICALL Java_com_westone_cardmanager_Card_RegCardStatusCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_westone_cardmanager_Card
 * Method:    Login
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_cardmanager_Card_Login
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_westone_cardmanager_Card
 * Method:    ChangePin
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_cardmanager_Card_ChangePin
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_westone_cardmanager_Card
 * Method:    ResetUserPinwithOTP
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_westone_cardmanager_Card_ResetUserPinwithOTP
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_westone_cardmanager_Card
 * Method:    GetRemainLockedTimes
 * Signature: (Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_westone_cardmanager_Card_GetRemainLockedTimes
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_westone_cardmanager_Card
 * Method:    VerifyPin
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_cardmanager_Card_VerifyPin
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_westone_cardmanager_Card
 * Method:    GetCardVersionInfo
 * Signature: (Ljava/lang/String;)Lcom/westone/cardmanager/JniCardInfo;
 */
JNIEXPORT jobject JNICALL Java_com_westone_cardmanager_Card_GetCardVersionInfo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_westone_cardmanager_Card
 * Method:    softCreateCipherCard
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_westone_cardmanager_Card_softCreateCipherCard
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_westone_cardmanager_Card
 * Method:    DestroyCipherCard
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_westone_cardmanager_Card_DestroyCipherCard
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
