#ifndef _LINUX_MACRO_
typedef CK_ULONG CK_EXTEND_TYPE;
#else
typedef CK_UINT CK_EXTEND_TYPE;
#endif



typedef struct CK_EXTEND_IN_STRUCT { 
	CK_EXTEND_TYPE extendType; 
	CK_VOID_PTR pParameter; 
#ifndef _LINUX_MACRO_
	CK_ULONG ulParameterLen; 
#else
	CK_UINT ulParameterLen;
#endif
} CK_EXTEND_IN;

typedef struct CK_EXTEND_OUT_STRUCT { 
	CK_EXTEND_TYPE extendType; 
	CK_VOID_PTR pParameter; 
#ifndef _LINUX_MACRO_
	CK_ULONG ulParameterLen; 
#else
	CK_UINT ulParameterLen;
#endif
} CK_EXTEND_OUT;

typedef CK_EXTEND_IN CK_PTR CK_EXTEND_IN_PTR;
typedef CK_EXTEND_OUT CK_PTR CK_EXTEND_OUT_PTR;

#define CK_EXTEND_BASE                         0x00000000
#define CK_EXTEND_VERIFYPIN                    CK_EXTEND_BASE+1
#define CK_EXTEND_GETSN                        CK_EXTEND_BASE+2
#define CK_EXTEND_GETPINTIME                   CK_EXTEND_BASE+3
#define CK_EXTEND_GETSDSTATUS                  CK_EXTEND_BASE+4
#define CK_EXTEND_GETEXCHANGEPUBKEY            CK_EXTEND_BASE+5
#define CK_EXTEND_GETEXCHANGESESSKEY           CK_EXTEND_BASE+6
#define CK_EXTEND_SETMONITORSM2PUBKEY          CK_EXTEND_BASE+7
#define CK_EXTEND_SETBASEKEY                   CK_EXTEND_BASE+8
#define CK_EXTEND_ENCRYPTBYSK                  CK_EXTEND_BASE+9
#define CK_EXTEND_DECRYPTBYSK                  CK_EXTEND_BASE+10
#define CK_EXTEND_GETSK                        CK_EXTEND_BASE+11
#define CK_EXTEND_SETSM3KDFBASEKEY             CK_EXTEND_BASE+12
#define CK_EXTEND_GETLOGINSTATE                CK_EXTEND_BASE+13
#define CK_EXTEND_SETDESTROYKEY                CK_EXTEND_BASE+14
#define CK_EXTEND_DODESTROY                    CK_EXTEND_BASE+15
#define CK_EXTEND_RESET_USERPIN                CK_EXTEND_BASE+16
#define CK_EXTEND_RESET_OTPPIN                 CK_EXTEND_BASE+17
#define CK_EXTEND_GETOTPTIME_USABLE            CK_EXTEND_BASE+18
#define CK_EXTEND_GETOTPTIME_TRY               CK_EXTEND_BASE+19
#define CK_EXTEND_REMOTE_SET_DATA              CK_EXTEND_BASE+20
#define CK_EXTEND_REMOTE_GET_DATAVER           CK_EXTEND_BASE+21
#define CK_EXTEND_END                          CK_EXTEND_BASE+22


#define CKA_ECC_BITS_LEN 	 CKA_VENDOR_DEFINED+1//CK_ULONG
#define CKA_ECC_X_COORDINATE CKA_VENDOR_DEFINED+2//Big integer
#define CKA_ECC_Y_COORDINATE CKA_VENDOR_DEFINED+3//Big integer
#define CKA_ECC_PRIVATE 	 CKA_VENDOR_DEFINED+4//Big integer


//��־�������
typedef enum{
        CK_LOG_FATAL = 1,
        CK_LOG_ERROR = 2,
        CK_LOG_WARNING = 3,
        CK_LOG_INFO = 4,
        CK_LOG_DEBUG = 5,
        CK_LOG_VERBOSE = 6
} CK_LOG_SEVERITY;
typedef CK_CALLBACK_FUNCTION(void, CK_LOGGER)(CK_LOG_SEVERITY severity, const char* func, unsigned int line, const char* file, const char* format, ...);



#define CK_CARD_STATUS_CLOSE			    0x00000000 
#define CK_CARD_STATUS_INTEGRITY		    0x00000101        
#define CK_CARD_STATUS_ALG_TEST			    0x00000102  

#define CK_CARD_STATUS_OPER_AUTH		    0x00000200  
#define CK_CARD_STATUS_SO			        0x00000201       
#define CK_CARD_STATUS_USER			        0x00000203       
#define CK_CARD_STATUS_SAFETY_SERVICE		0x00000204  

#define CK_CARD_STATUS_ERROR_INTEGRITY		0x00000301  
#define CK_CARD_STATUS_ERROR_ALG_TEST		0x00000302  
#define CK_CARD_STATUS_ERROR_USER_LOCKED	0x00000303       
#define CK_CARD_STATUS_ERROR_SO_LOCKED		0x00000304       
#define CK_CARD_STATUS_ERROR_SAFETY_SERVICE	0x00000305       
#define CK_CARD_STATUS_ERROR_DESTORY		0x00000306  
#define CK_CARD_STATUS_ERROR_UNKNOWN        0x0000ffff

#define CKR_WST_SCM_DEFINED  (CKR_VENDOR_DEFINED + 0x100)
#define CKR_ERR_CHANNEL_INIT (CKR_WST_SCM_DEFINED + 1)
#define CKR_ERR_CHANNEL_CONNECT (CKR_WST_SCM_DEFINED + 2)
#define CKR_ERR_CHANNEL_SEND (CKR_WST_SCM_DEFINED + 3)
#define CKR_ERR_CHANNEL_RECV (CKR_WST_SCM_DEFINED + 4)
#define CKR_ERR_CHANNEL_CERT_FILE (CKR_WST_SCM_DEFINED + 5)
#define CKR_ERR_CHANNEL_LOAD_ENGINE (CKR_WST_SCM_DEFINED + 6)
#define CKR_ERR_COOPERATE_TOKEN_NOT_READY (CKR_WST_SCM_DEFINED + 22)

#define CKR_ERR_LIC_REQUEST (CKR_WST_SCM_DEFINED + 30)
#define CKR_ERR_LIC_TOKEN_IS_INVALID (CKR_WST_SCM_DEFINED + 31)
#define CKR_ERR_LIC_TOKEN_ALREADY_OVERDUE (CKR_WST_SCM_DEFINED + 32)
#define CKR_ERR_ALL_LIC_CODE_ARE_EXPIRED_OR_USE_UP (CKR_WST_SCM_DEFINED + 33)




