/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_westone_csmmanager_P11TestNative */

#ifndef _Included_com_westone_csmmanager_P11TestNative
#define _Included_com_westone_csmmanager_P11TestNative
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_westone_csmmanager_P11TestNative
 * Method:    BaseFunctionTest
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/westone/csmmanager/TFStatus;)Lcom/westone/csmmanager/ReturnInfo;
 */
JNIEXPORT jobject JNICALL Java_com_westone_csmmanager_P11TestNative_BaseFunctionTest
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_westone_csmmanager_P11TestNative
 * Method:    ObjFunctionTest
 * Signature: ()Lcom/westone/csmmanager/ReturnInfo;
 */
JNIEXPORT jobject JNICALL Java_com_westone_csmmanager_P11TestNative_ObjFunctionTest
  (JNIEnv *, jclass);

/*
 * Class:     com_westone_csmmanager_P11TestNative
 * Method:    KeyFunctionTest
 * Signature: ()Lcom/westone/csmmanager/ReturnInfo;
 */
JNIEXPORT jobject JNICALL Java_com_westone_csmmanager_P11TestNative_KeyFunctionTest
  (JNIEnv *, jclass);

/*
 * Class:     com_westone_csmmanager_P11TestNative
 * Method:    EncFunctionTest
 * Signature: ()Lcom/westone/csmmanager/ReturnInfo;
 */
JNIEXPORT jobject JNICALL Java_com_westone_csmmanager_P11TestNative_EncFunctionTest
  (JNIEnv *, jclass);

/*
 * Class:     com_westone_csmmanager_P11TestNative
 * Method:    DigFunctionTest
 * Signature: ()Lcom/westone/csmmanager/ReturnInfo;
 */
JNIEXPORT jobject JNICALL Java_com_westone_csmmanager_P11TestNative_DigFunctionTest
  (JNIEnv *, jclass);

/*
 * Class:     com_westone_csmmanager_P11TestNative
 * Method:    SignFunctionTest
 * Signature: ()Lcom/westone/csmmanager/ReturnInfo;
 */
JNIEXPORT jobject JNICALL Java_com_westone_csmmanager_P11TestNative_SignFunctionTest
  (JNIEnv *, jclass);

/*
 * Class:     com_westone_csmmanager_P11TestNative
 * Method:    RndFunctionTest
 * Signature: ()Lcom/westone/csmmanager/ReturnInfo;
 */
JNIEXPORT jobject JNICALL Java_com_westone_csmmanager_P11TestNative_RndFunctionTest
  (JNIEnv *, jclass);

/*
 * Class:     com_westone_csmmanager_P11TestNative
 * Method:    ExtFunctionTest
 * Signature: ()Lcom/westone/csmmanager/ReturnInfo;
 */
JNIEXPORT jobject JNICALL Java_com_westone_csmmanager_P11TestNative_ExtFunctionTest
  (JNIEnv *, jclass);

JNIEXPORT jobject JNICALL Java_com_westone_csmmanager_P11TestNative_SCSetUp
        (JNIEnv *, jclass);

JNIEXPORT jobject JNICALL Java_com_westone_csmmanager_P11TestNative_CallTest
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_westone_csmmanager_P11TestNative_testThreadRun
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_westone_csmmanager_P11TestNative
 * Method:    SM2Test
 * Signature: (II)Lcom/westone/csmmanager/PerReturnInfo;
 */
JNIEXPORT jobject JNICALL Java_com_westone_csmmanager_P11TestNative_SM2Test
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_westone_csmmanager_P11TestNative
 * Method:    SM4Test
 * Signature: (II)Lcom/westone/csmmanager/PerReturnInfo;
 */
JNIEXPORT jobject JNICALL Java_com_westone_csmmanager_P11TestNative_SM4Test
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_westone_csmmanager_P11TestNative
 * Method:    ZucTest
 * Signature: (II)Lcom/westone/csmmanager/PerReturnInfo;
 */
JNIEXPORT jobject JNICALL Java_com_westone_csmmanager_P11TestNative_ZucTest
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
